###
GET http://localhost:3466/

###
HEAD http://localhost:3466/

###
GET http://localhost:3466/
Authorization: Basic admin admin

###
GET http://localhost:3466/non_existing_page
Authorization: Basic admin admin

###
HEAD http://localhost:3466/
Authorization: Basic admin admin

###
OPTIONS http://localhost:3466/
Authorization: Basic admin admin

###
GET http://localhost:3466/products
Authorization: Basic admin admin

###
HEAD http://localhost:3466/products
Authorization: Basic admin admin

###
OPTIONS http://localhost:3466/products
Authorization: Basic admin admin

###
GET http://localhost:3466/help
Authorization: Basic admin admin
###
OPTIONS http://localhost:3466/help
Authorization: Basic admin admin

###
POST http://localhost:3466/products
Authorization: Basic admin admin
Content-Type: application/x-www-form-urlencoded

name=NewProduct&quantity=90000&man_id=999999

###
POST http://localhost:3466/products
Authorization: Basic admin admin
Content-Type: application/x-www-form-urlencoded

name=SecondProduct&quantity=555&man_id=999999

###
POST http://localhost:3466/products/delete
Authorization: Basic admin admin
Content-Type: application/x-www-form-urlencoded

nameToDelete=NewProduct

###
GET http://localhost:3466
Authorization: Basic user user

###
HEAD http://localhost:3466
Authorization: Basic user user

###
OPTIONS http://localhost:3466
Authorization: Basic user user

###
GET http://localhost:3466/products
Authorization: Basic user user

###
GET http://localhost:3466/help
Authorization: Basic user user

###
POST http://localhost:3466/products
Authorization: Basic user user
Content-Type: application/x-www-form-urlencoded

name=NewProduct&quantity=90000&man_id=999999

